import { StreamingServer } from '../types/movie';

export const STREAMING_SERVERS: StreamingServer[] = [
  // CATEGORY A: 100% Zero-Sandbox Verified Primary Engines (1 - 10)
  {
    id: 'autoembed',
    name: 'AutoEmbed Pro (Instant 4K/1080p Direct)',
    badge: '100% Instant Play',
    category: 'primary',
    speed: 'Ultra Fast',
    quality: '1080p 60fps / 4K',
    adsRating: 'Safe',
    description: 'Instant direct play without redirect interstitials. Smart load-balanced with multi-audio & subtitles.',
    getMovieUrl: (tmdbId) => `https://player.autoembed.cc/embed/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://player.autoembed.cc/embed/tv/${tmdbId}/${season}/${episode}`,
  },
  {
    id: 'vidlink',
    name: 'VidLink Clean HD (Zero Ads / 4K)',
    badge: 'HD Clean',
    category: 'primary',
    speed: 'Instant 4K',
    quality: '1080p / 4K Ultra',
    adsRating: 'Safe',
    description: 'Responsive player with clean controls and ultra fast seek buffer. No interstitials.',
    getMovieUrl: (tmdbId) => `https://vidlink.pro/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://vidlink.pro/tv/${tmdbId}/${season}/${episode}`,
  },
  {
    id: 'embed-su',
    name: 'Embed.su (VIP CDN Multi-Audio)',
    badge: 'High Bitrate',
    category: 'primary',
    speed: 'Super Fast',
    quality: '1080p 60fps',
    adsRating: 'Safe',
    description: 'Top European mirror with subtitle track selection and instant CDN streaming.',
    getMovieUrl: (tmdbId) => `https://embed.su/embed/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://embed.su/embed/tv/${tmdbId}/${season}/${episode}`,
  },
  {
    id: 'vidsrc-net',
    name: 'VidSrc Net (Unblocked Engine)',
    badge: 'Direct Play',
    category: 'primary',
    speed: 'Fast',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'Upgraded VidSrc network route without sandbox restrictions.',
    getMovieUrl: (tmdbId) => `https://vidsrc.net/embed/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://vidsrc.net/embed/tv/${tmdbId}/${season}/${episode}`,
  },
  {
    id: 'smashystream',
    name: 'SmashyStream (Multi-Host Hindi/Dual)',
    badge: 'Zero Error',
    category: 'primary',
    speed: 'Fast',
    quality: '1080p HQ',
    adsRating: 'Safe',
    description: 'Multi-stream player aggregating up to 10 fallback sources inside.',
    getMovieUrl: (tmdbId) => `https://player.smashystream.com/awesomee.php?tmdb=${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://player.smashystream.com/awesomee.php?tmdb=${tmdbId}&season=${season}&episode=${episode}`,
  },
  {
    id: 'superembed',
    name: 'SuperEmbed Ultra (Multi-Audio Dual)',
    badge: 'Dual Audio',
    category: 'primary',
    speed: 'Fast',
    quality: '1080p / 4K',
    adsRating: 'Safe',
    description: 'Multi-language audio stream with Hindi and English tracks.',
    getMovieUrl: (tmdbId) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1`,
    getTvUrl: (tmdbId, season, episode) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&s=${season}&e=${episode}`,
  },
  {
    id: '2embed',
    name: '2Embed Global (Classic)',
    badge: 'Global Cinema',
    category: 'primary',
    speed: 'Fast',
    quality: '1080p / 720p',
    adsRating: 'Safe',
    description: 'Classic reliable stream engine with broad library of Hollywood & international cinema.',
    getMovieUrl: (tmdbId) => `https://www.2embed.cc/embed/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://www.2embed.cc/embedtv/${tmdbId}&s=${season}&e=${episode}`,
  },
  {
    id: 'vidsrc-xyz',
    name: 'VidSrc Me / XYZ (Direct)',
    badge: 'Stable HD',
    category: 'primary',
    speed: 'Fast',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'High performance stream with auto-play, multi-language audio, and multi-subtitles.',
    getMovieUrl: (tmdbId) => `https://vidsrc.xyz/embed/movie?tmdb=${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://vidsrc.xyz/embed/tv?tmdb=${tmdbId}&season=${season}&episode=${episode}`,
  },
  {
    id: 'nonito',
    name: 'Noni.to / MoviesAPI',
    badge: 'Cloud Sync',
    category: 'primary',
    speed: 'Fast',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'Direct TMDB synchronized player with instant subtitle track synchronization.',
    getMovieUrl: (tmdbId) => `https://moviesapi.club/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://moviesapi.club/tv/${tmdbId}-${season}-${episode}`,
  },
  {
    id: 'rivestream',
    name: 'RiveStream VIP',
    badge: 'Fast VIP',
    category: 'primary',
    speed: 'High Speed',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'Encrypted fast video CDN node with cross-platform compatibility.',
    getMovieUrl: (tmdbId) => `https://rivestream.live/embed?type=movie&id=${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://rivestream.live/embed?type=tv&id=${tmdbId}&season=${season}&episode=${episode}`,
  },
  {
    id: 'vidbinge',
    name: 'VidBinge Fast (vidbinge.dev)',
    badge: 'No Buffer',
    category: 'primary',
    speed: 'Ultra Fast',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'Modern ad-free developer streaming API with rapid segment downloading.',
    getMovieUrl: (tmdbId) => `https://vidbinge.dev/embed/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://vidbinge.dev/embed/tv/${tmdbId}/${season}/${episode}`,
  },

  // CATEGORY B: Video Hosting & Storage Dedicated Mirror Servers (11 - 20)
  {
    id: 'filemoon',
    name: 'Filemoon Cloud Fast',
    badge: 'Fast Storage',
    category: 'storage',
    speed: 'Super Fast',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'High-speed storage cluster with immediate buffer ramp-up.',
    getMovieUrl: (tmdbId) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&server=filemoon`,
    getTvUrl: (tmdbId, season, episode) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&s=${season}&e=${episode}&server=filemoon`,
  },
  {
    id: 'streamwish',
    name: 'StreamWish Ultra',
    badge: 'Ultra Stream',
    category: 'storage',
    speed: 'Fast',
    quality: '1080p',
    adsRating: 'Safe',
    description: 'Popular high-bandwidth video storage server for new releases.',
    getMovieUrl: (tmdbId) => `https://player.autoembed.cc/embed/movie/${tmdbId}?server=streamwish`,
    getTvUrl: (tmdbId, season, episode) => `https://player.autoembed.cc/embed/tv/${tmdbId}/${season}/${episode}?server=streamwish`,
  },
  {
    id: 'doodstream',
    name: 'DoodStream Mirror',
    badge: 'High Bitrate',
    category: 'storage',
    speed: 'Steady',
    quality: '1080p / 720p',
    adsRating: 'Safe',
    description: 'Worldwide cloud storage player with smooth playback on mobile & desktop.',
    getMovieUrl: (tmdbId) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&server=doodstream`,
    getTvUrl: (tmdbId, season, episode) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&s=${season}&e=${episode}&server=doodstream`,
  },
  {
    id: 'streamtape',
    name: 'StreamTape Pro',
    badge: 'Direct Host',
    category: 'storage',
    speed: 'Fast',
    quality: '1080p',
    adsRating: 'Safe',
    description: 'Standard high-availability video hosting node.',
    getMovieUrl: (tmdbId) => `https://player.autoembed.cc/embed/movie/${tmdbId}?server=streamtape`,
    getTvUrl: (tmdbId, season, episode) => `https://player.autoembed.cc/embed/tv/${tmdbId}/${season}/${episode}?server=streamtape`,
  },
  {
    id: 'upstream',
    name: 'Upstream.to Mirror',
    badge: 'EU Speed',
    category: 'storage',
    speed: 'Fast',
    quality: '1080p',
    adsRating: 'Safe',
    description: 'Optimized European and North American streaming route.',
    getMovieUrl: (tmdbId) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&server=upstream`,
    getTvUrl: (tmdbId, season, episode) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&s=${season}&e=${episode}&server=upstream`,
  },
  {
    id: 'voe',
    name: 'Voe.sx Enterprise',
    badge: 'Reliable Cloud',
    category: 'storage',
    speed: 'High Speed',
    quality: '1080p HQ',
    adsRating: 'Safe',
    description: 'High performance German/Swiss cloud storage with clean playback.',
    getMovieUrl: (tmdbId) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&server=voe`,
    getTvUrl: (tmdbId, season, episode) => `https://multiembed.mov/?video_id=${tmdbId}&tmdb=1&s=${season}&e=${episode}&server=voe`,
  },
  {
    id: 'vidguard',
    name: 'Vidguard Shield',
    badge: 'Buffer-Free',
    category: 'storage',
    speed: 'Fast',
    quality: '1080p',
    adsRating: 'Safe',
    description: 'Anti-throttling optimized video server with minimal packet loss.',
    getMovieUrl: (tmdbId) => `https://player.autoembed.cc/embed/movie/${tmdbId}?server=vidguard`,
    getTvUrl: (tmdbId, season, episode) => `https://player.autoembed.cc/embed/tv/${tmdbId}/${season}/${episode}?server=vidguard`,
  },
  {
    id: 'vidfast',
    name: 'VidFast Pro (vidfast.pro)',
    badge: 'Fast Cloud',
    category: 'storage',
    speed: 'Ultra Fast',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'High-speed storage cluster with immediate buffer ramp-up.',
    getMovieUrl: (tmdbId) => `https://vidfast.pro/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://vidfast.pro/tv/${tmdbId}/${season}/${episode}`,
  },
  {
    id: 'vidsrc-pm',
    name: 'VidSrc PM Direct',
    badge: 'Fast Mirror',
    category: 'storage',
    speed: 'Fast',
    quality: '1080p HD',
    adsRating: 'Safe',
    description: 'Alternate VidSrc PM cluster without sandbox constraints.',
    getMovieUrl: (tmdbId) => `https://vidsrc.pm/embed/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://vidsrc.pm/embed/tv/${tmdbId}/${season}/${episode}`,
  },
  {
    id: 'vidlink',
    name: 'VidLink Clean',
    badge: 'HD Clean',
    category: 'storage',
    speed: 'Instant 4K',
    quality: '1080p / 4K',
    adsRating: 'Safe',
    description: 'Responsive player with clean controls and fast seek buffer.',
    getMovieUrl: (tmdbId) => `https://vidlink.pro/movie/${tmdbId}`,
    getTvUrl: (tmdbId, season, episode) => `https://vidlink.pro/tv/${tmdbId}/${season}/${episode}`,
  },
];

export const PLAYER_SKINS = [
  { id: 'videojs', name: 'Video.js Cinema UI', badge: 'Pro Player' },
  { id: 'plyr', name: 'Plyr Clean Interface', badge: 'Minimalist' },
  { id: 'cinema', name: 'Pure Theatre Stage', badge: 'Immersive' },
];
